/* All source and model text is escaped before display. No content becomes executable instructions. */
let state, currentCase, currentAction, activeTab = 'today';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = value => new Date(value).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Los_Angeles'});
const day = value => new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/Los_Angeles'});
const badge = status => `<span class="status ${esc(status)}">${esc(status.replaceAll('_',' '))}</span>`;
const empty = message => `<div class="empty">${esc(message)}</div>`;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').hidden=true,9000);}
async function api(path, body={}, method='POST'){
  const response=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-Mom-CSRF':state?.csrf||''},...(method==='GET'?{}:{body:JSON.stringify(body)})});
  const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;
}
async function refresh(){state=await api('/state',{},'GET');render();}
function tab(name){activeTab=name;document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('page-label').textContent=name.toUpperCase();window.scrollTo({top:0,behavior:'smooth'});}
function render(){
  const chosen=$('scenario').value||state.scenario.id;
  $('scenario').innerHTML=Object.entries(state.scenarios).map(([key,label])=>`<option value="${esc(key)}">${esc(label)}</option>`).join('');$('scenario').value=chosen;
  const records=state.records.filter(r=>r.status==='current');
  $('agenda').innerHTML=records.map(r=>`<div class="event"><div class="event-time">${fmt(r.start)}<small>${day(r.start)} · until ${fmt(r.end)}</small></div><div class="event-title"><h3>${esc(r.title)}</h3><p>${esc(r.location)} · ${esc(r.source)}</p></div><span class="child-tag">${esc(r.child||'Child unclear')}</span>${badge('current')}</div>`).join('')||empty('No current records. Check the source status.');
  $('roles').innerHTML=state.roles.map((r,i)=>`<div class="role"><div class="role-number">0${i+1}</div><h3>${esc(r.name)}</h3><p>${esc(r.purpose)}</p></div>`).join('');
  $('source-list').innerHTML=state.records.map(r=>`<article class="card source-card"><div><div class="section-top"><h3>${esc(r.title)}</h3>${badge(r.status)}</div><dl class="metadata"><dt>Source</dt><dd>${esc(r.source)} · ${esc(r.id)}</dd><dt>Family member</dt><dd>${esc(r.child||'Unclear — needs review')}</dd><dt>When</dt><dd>${day(r.start)} · ${fmt(r.start)}–${fmt(r.end)}</dd><dt>Revision</dt><dd>${r.revision}</dd><dt>Retrieved</dt><dd>${esc(r.retrieved_at)}</dd><dt>Preparation</dt><dd>${esc(r.preparation.join(', ')||'None listed')}</dd></dl></div><div class="source-text">${esc(r.text)}</div></article>`).join('');
  renderCase();renderDecisions();
  $('action-list').innerHTML=state.actions.slice().reverse().map(a=>`<article class="card"><div class="section-top"><h3>Local calendar change</h3>${badge(a.status)}</div><p class="muted">${esc(a.id)} · ${esc(a.target)}</p><p>${a.approved_at?'Exact approval recorded.':'Awaiting your specific approval.'} ${a.verified_at?'Local write verified.':''}</p></article>`).join('')||empty('No actions yet. Check the family plan and preview a feasible alternative.');
  $('task-list').innerHTML=state.tasks.map(t=>`<article class="card task"><div><h3>${esc(t.title)}</h3>${badge(t.status)}<p class="muted">${esc(t.source_ids.join(' · '))}${t.snooze_until?' · Snoozed until '+esc(t.snooze_until):''}</p></div><div class="task-actions">${['acknowledged','completed','snoozed','incorrect','rescheduled'].map(s=>`<button class="secondary" data-feedback="${s}" data-task="${esc(t.id)}">${{acknowledged:'Got it',completed:'Done',snoozed:'Snooze 1h',incorrect:'Incorrect',rescheduled:'Rescheduled'}[s]}</button>`).join('')}</div></article>`).join('')||empty('Send a simulated notification to create a follow-up task.');
  $('notification-list').innerHTML=state.notifications.slice().reverse().map(n=>`<article class="card notification"><div class="section-top"><h3>${n.channel==='simulation'?'Simulated family notification':'Telegram notification'}</h3>${badge(n.status)}</div><p>${esc(n.text)}</p></article>`).join('')||empty('The outbox is quiet. No messages have been sent.');
  $('calendar-list').innerHTML=state.calendar.map(c=>`<article class="card"><h3>${esc(c.event_id)}</h3><p>${esc(c.type)}${c.start?' · '+day(c.start)+' '+fmt(c.start)+'–'+fmt(c.end):''}</p><p class="muted">Verified locally · ${esc(c.verified_at)}. Source provider remains unchanged.</p></article>`).join('')||empty('No local calendar changes have been applied.');
  $('audit-list').innerHTML=state.audit.map(a=>`<div class="audit-entry">${esc(a.at)} · ${esc(a.kind)} · ${esc(a.ref)}<br>${esc(JSON.stringify(a.body))}</div>`).join('');
  $('reflection-list').innerHTML=state.reflections.slice().reverse().map(r=>`<article class="card"><div class="section-top"><h2>${esc(r.period)}</h2>${badge('local_preview')}</div><div class="metrics">${[['cases_reviewed','Cases reviewed'],['blocked_cases','Checks needing attention'],['verified_local_actions','Verified local actions'],['simulated_notifications','Simulated notifications'],['completed_tasks','Completed tasks'],['delivery_unknown','Unverified deliveries']].map(([k,label])=>`<div class="metric"><strong>${r[k]}</strong><span>${label}</span></div>`).join('')}</div><p>${esc(r.recommendation)}</p><p class="muted">${esc(r.publication)} · Hard rules unchanged</p></article>`).join('')||empty('Create a reflection after running a few scenarios.');
  $('connection-list').innerHTML=[['BYGA & LingoAce','Synthetic schedule fixtures','Use exported records or authorized email notifications for later live access.'],['Gmail & Google Calendar','Read-only setup available','Run the Google OAuth setup guide. The running demo has no access to your accounts.'],['Telegram',state.connections.telegram_consent?'Standing permission enabled':state.connections.telegram_configured?'Configured; standing permission required':'Not connected','The default outbox is simulated. Real notifications require a specific approved chat.'],['Model-assisted review',state.connections.model_configured?'Configured; click review to opt in':'Not configured','Optional OpenAI review uses read-only tools. Deterministic facts and approval checks stay authoritative.']].map(([title,status,description])=>`<article class="card"><div class="section-top"><h2>${esc(title)}</h2>${badge(status.toLowerCase().replaceAll(' ','_').replaceAll(';',''))}</div><p>${esc(description)}</p></article>`).join('');
}
function renderCase(){
 if(!currentCase){$('case-result').innerHTML='';return;}
 const c=currentCase;
 $('case-result').innerHTML=`<article class="card result ${esc(c.status)}"><div class="section-top"><span class="eyebrow">YOUR CHECK IS READY</span>${badge(c.status)}</div><h2>${c.status==='blocked'?'One piece is still missing.':c.conflicts.length?'A little schedule untangling.':c.advice?'A thoughtful look ahead.':'Room for everything.'}</h2><p>${esc(c.answer)}</p><p class="muted">${c.elapsed_ms} ms · ${c.source_ids.length} current records · Fixed synthetic dates</p><div class="result-actions">${c.planning?'<button class="primary" data-go="decisions">Review the alternatives ↗</button>':''}${c.status!=='blocked'?'<button class="secondary" id="simulate-notification">Send simulated notification</button>':''}${state.connections.model_configured?'<button class="secondary" id="model-review">Request model review</button>':''}</div><details class="trace"><summary>See how the assistant checked this</summary>${c.trace.map(t=>`<div class="trace-step"><strong>${esc(t.agent)} · ${esc(t.stage)}</strong><span>${esc(t.observation)}</span></div>`).join('')}</details>${c.evidence.length?`<details class="trace"><summary>View the three retrieval results</summary>${c.evidence.map(e=>`<div class="trace-step"><strong>${esc(e.record.id)} · ${esc(e.record.status)}</strong><span>${esc(e.record.text)} (similarity ${e.similarity})</span></div>`).join('')}</details>`:''}</article>`;
}
function renderDecisions(){
 const c=currentCase;
 if(c?.advice){$('decision-list').innerHTML=`<article class="card"><h2>Start with the student's goals</h2><p>${esc(c.advice.summary)}</p>${c.advice.planning_template.map(m=>`<div class="event"><h3>${esc(m.year)}</h3><p>${esc(m.focus)}</p></div>`).join('')}<p class="muted">Discussion template only. Official requirements and dates remain unverified.</p></article>`;return;}
 if(!c?.planning){$('decision-list').innerHTML=empty('Run a schedule check to compare plans. Simple reminders bypass the planning search.');return;}
 $('decision-list').innerHTML=`<div class="card"><h2>${c.planning.recommendations.length?'A feasible option to consider':'Your input is needed'}</h2><p>${c.planning.expansions} candidate actions evaluated. Hard rules checked before scores. ${c.planning.needs_parent_choice?'Parent selection or more evidence is required.':'The highest-scoring feasible option appears first.'}</p><p class="muted">Limits: 4 branches · 3 retained plans · 3 levels · 28 expansions · 8 seconds</p></div>`+c.planning.branches.slice().sort((a,b)=>(a.verdict==='feasible'?-1:1)-(b.verdict==='feasible'?-1:1)||b.score-a.score).map(b=>`<article class="card candidate"><div>${badge(b.verdict)}<h2>${esc(b.title)}</h2><p>Evidence: ${esc(b.source_ids.join(' · '))}</p>${b.changes.map(change=>`<p>${esc(change.type)} ${esc(change.event_id)}${change.start?' → '+day(change.start)+' '+fmt(change.start)+'–'+fmt(change.end):''}</p>`).join('')}${b.hard_rule_failures.map(r=>`<p class="reasons">${esc(r)}</p>`).join('')}${b.unresolved.map(r=>`<p>${esc(r)}</p>`).join('')}${b.verdict==='feasible'?`<button class="primary" data-preview="${esc(b.id)}">Preview exact local action</button>`:''}<details class="trace"><summary>Score breakdown & branch record</summary><pre>${esc(JSON.stringify({id:b.id,parent_id:b.parent_id,depth:b.depth,components:b.components},null,2))}</pre></details></div><div class="score">${b.score}<small>OUT OF 100</small></div></article>`).join('');
}
async function ask(){const button=$('ask-button');button.disabled=true;button.textContent='Checking sources…';try{currentCase=await api('/ask',{query:$('query').value});await refresh();}finally{button.disabled=false;button.textContent="Check my family's plans ↗";}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.tab)tab(b.dataset.tab);
 if(b.dataset.go)tab(b.dataset.go);
 if(b.dataset.query){$('query').value=b.dataset.query;await ask();}
 if(b.id==='load-scenario'){await api('/scenarios/'+$('scenario').value);currentCase=null;await refresh();$('query').value=$('scenario').value==='college'?'Help me prepare a high school and college planning discussion.':'Did BYGA change soccer this week, and does it conflict with LingoAce Chinese class?';toast('Scenario loaded. Check the plan to see how the assistant responds.');}
 if(b.dataset.preview){currentAction=await api(`/cases/${currentCase.id}/preview/${b.dataset.preview}`);$('approval-payload').textContent=JSON.stringify({target:currentAction.target,changes:currentAction.changes,expires_at:currentAction.expires_at},null,2);$('approval-status').textContent='';$('approve-check').checked=false;$('approve-execute').disabled=true;$('approval-dialog').showModal();}
 if(b.id==='try-blocked'){await api(`/actions/${currentAction.id}/execute`);}
 if(b.id==='approve-execute'){if(!$('approve-check').checked)return;b.disabled=true;try{await api('/actions/approve',{action_id:currentAction.id,confirmation:'I approve this exact action'});await api(`/actions/${currentAction.id}/execute`);$('approval-dialog').close();await refresh();toast('Approved action applied and verified in the local demonstration calendar.');}catch(err){b.disabled=false;throw err;}}
 if(b.id==='simulate-notification'){const result=await api(`/cases/${currentCase.id}/notify`);await refresh();toast('Notification: '+result.status.replaceAll('_',' ')+(result.reason?' · '+result.reason:''));}
 if(b.dataset.feedback){await api(`/tasks/${b.dataset.task}/feedback`,{status:b.dataset.feedback,minutes:60});await refresh();toast('Feedback saved.');}
 if(b.id==='reflect'){await api('/reflection');await refresh();toast('Weekly reflection saved locally.');}
 if(b.id==='import-record'){await api('/records',JSON.parse($('record-json').value));await refresh();toast('Record saved. Run a fresh check to use the updated evidence.');}
 if(b.id==='model-review'){b.disabled=true;try{const review=await api(`/cases/${currentCase.id}/model-review`);const box=document.createElement('article');box.className='card';const title=document.createElement('h2');title.textContent='Model review · requires your review';const text=document.createElement('p');text.textContent=review.text||review.detail;$('case-result').append(box);box.append(title,text);}finally{b.disabled=false;}}
}catch(err){if($('approval-dialog').open)$('approval-status').textContent=err.message;else toast(err.message);}});
$('ask-form').addEventListener('submit',async e=>{e.preventDefault();try{await ask();}catch(err){if($('approval-dialog').open)$('approval-status').textContent=err.message;else toast(err.message);}});
$('approve-check').addEventListener('change',e=>$('approve-execute').disabled=!e.target.checked);
refresh().catch(e=>toast('Could not load the assistant: '+e.message));
